# ERT Covert gear - basically, nukeops in disguise
- type: startingGear
  id: ERTCovertGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTOfficer
    shoes: ClothingShoesBootsCombatFilled #no magboots?
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurityAlt
    id: SyndiPDANukie #chameleon this before you go
    ears: ClothingHeadsetAltSecurityRegular #no cc channel
    belt: ClothingBeltAssaultFilled
    pocket2: FlashlightSeclite
  storage:
    back:
    - MedkitCombatFilled
    - CrowbarRed

# ERT Covert Leader gear
- type: startingGear
  id: ERTLeaderCovertGearFull
  parent: ERTCovertGearFull
  equipment:
    back: ClothingBackpackERTLeader
    neck: SyndicateWhistle
    outerClothing: ClothingOuterHardsuitERTLeaderAlt

