- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/_Reserve/Guidebook/Security/Security.xml"
  children:
  - Forensics
  - Defusal
  - CriminalRecords
  - CorporateLaw # Corvax-Corporate-Law

- type: guideEntry
  id: Forensics
  name: guide-entry-forensics
  text: "/ServerInfo/_Reserve/Guidebook/Security/Forensics.xml"

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/_Reserve/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: CriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/_Reserve/Guidebook/Security/CriminalRecords.xml"

- type: guideEntry
  id: SpaceLaw
  name: guide-entry-rules-space-law
  text: "/ServerInfo/_Reserve/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml"
  children:
  - SpaceLawCrimeList

- type: guideEntry
  id: SpaceLawCrimeList
  name: guide-entry-rules-sl-crime-list
  text: "/ServerInfo/_Reserve/Guidebook/ServerRules/SpaceLaw/SLCrimeListReserve.xml"
