# SPDX-FileCopyrightText: 2025 Svarshik <96281939+lexaSvarshik@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: guideEntry
  id: Service
  name: guide-entry-service
  text: "/ServerInfo/_Reserve/Guidebook/Service/Service.xml"
  filterEnabled: True
  children:
  - Bartender
  - Botany
  - Chef
  - Janitorial

- type: guideEntry
  id: Bartender
  name: guide-entry-bartender
  text: "/ServerInfo/_Reserve/Guidebook/Service/Bartender.xml"
  filterEnabled: True

- type: guideEntry
  id: Botany
  name: guide-entry-botany
  text: "/ServerInfo/_Reserve/Guidebook/Service/Botany.xml"

- type: guideEntry
  id: Chef
  name: guide-entry-chef
  text: "/ServerInfo/_Reserve/Guidebook/Service/Chef.xml"

- type: guideEntry
  id: Janitorial
  name: guide-entry-janitorial
  text: "/ServerInfo/_Reserve/Guidebook/Service/Janitorial.xml"
